apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qid1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qid1
    app.kubernetes.io/part-of: ci10t-777-0019-app
  name: devfile-sample-qid1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qid1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qid1
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0019-tenant/ci10t-777-0019-app/devfile-sample-qid1@sha256:1e6c7764656ea1c73384d6b59b871325b4a60f463f920f6837e3e7afc2695e17
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
